In [1]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [2]:
def mean_absolute_error(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += abs(yt - yp)
    print("Total Error : ", total_error)
    mae = total_error / len(y_true)
    print("Mean absolute error :", mae)
    return mae

In [3]:
mean_absolute_error(y_true, y_predicted)

Total Error :  2.5
Mean absolute error : 0.5


0.5

In [4]:
y_predicted-y_true

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [5]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [6]:
np.mean(np.abs(y_predicted-y_true))

0.5

In [7]:
np.sum(np.abs(y_predicted-y_true))

2.5

In [8]:
np.log([0])

C:\Users\garvb\AppData\Local\Temp\ipykernel_30904\262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [9]:
np.log([0.0000000000000056])

array([-32.8160098])

In [10]:
epsilon = 1e-15

In [11]:
y_predicted

array([1, 1, 0, 0, 1])

In [12]:
y_predicted_new = [max(i, epsilon) for i in y_predicted]

In [13]:
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [14]:
y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [15]:
y_predicted_new = np.array([y_predicted_new])
np.log(y_predicted_new)

array([[-9.99200722e-16, -9.99200722e-16, -3.45387764e+01,
        -3.45387764e+01, -9.99200722e-16]])

In [17]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [18]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i, epsilon) for i in y_predicted]
    y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array([y_predicted_new])
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [19]:
log_loss(y_true, y_predicted)

17.2696280766844

### Mean Sqaured Error

In [28]:
def mse(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += (yt-yp)**2
    print("Total Squared error : ", total_error)
    mse = total_error/len(y_true)
    print("Mean Sq Error : ", mse)
    return mse

In [29]:
mse(y_true, y_predicted)

Total Squared error :  1.83
Mean Sq Error :  0.366


0.366

### By using Numpy

In [31]:
np.mean(np.square(y_true-y_predicted))

0.366