In [1]:
import numpy as np

In [2]:
revenue = np.array([[180,200,220], [24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [3]:
revenue

array([[180, 200, 220],
       [ 24,  36,  40],
       [ 12,  18,  20]])

In [4]:
expenses

array([[ 80,  90, 100],
       [ 10,  16,  20],
       [  8,  10,  10]])

In [5]:
profit = revenue - expenses

In [6]:
print(profit)

[[100 110 120]
 [ 14  20  20]
 [  4   8  10]]


In [7]:
units = np.array([[30,40,50], [5,10,15], [2,5,7]])
price = np.array([1000,400,1200])

In [8]:
units

array([[30, 40, 50],
       [ 5, 10, 15],
       [ 2,  5,  7]])

In [9]:
price

array([1000,  400, 1200])

In [10]:
price_per_unit = units*price

In [12]:
#price_per_unit

In [13]:
np.dot(price, units)

array([34400, 50000, 64400])

### Exercises

In [14]:
revenue_in_dollars = np.array([[200,220,250], [68,79,105], [110,140,180], [80,85,90]])
revenue_in_dollars

array([[200, 220, 250],
       [ 68,  79, 105],
       [110, 140, 180],
       [ 80,  85,  90]])

In [17]:
revenue_in_rupees = revenue_in_dollars*75

In [18]:
print(revenue_in_rupees)

[[15000 16500 18750]
 [ 5100  5925  7875]
 [ 8250 10500 13500]
 [ 6000  6375  6750]]


In [19]:
type(revenue_in_rupees)

numpy.ndarray

In [20]:
print(revenue_in_rupees)

[[15000 16500 18750]
 [ 5100  5925  7875]
 [ 8250 10500 13500]
 [ 6000  6375  6750]]


In [21]:
units_sold = np.array([[50,60,25], [10,13,5], [40,70,52]])
units_sold

array([[50, 60, 25],
       [10, 13,  5],
       [40, 70, 52]])

In [22]:
price_per_unit = np.array([20,30,15])
price_per_unit

array([20, 30, 15])

In [26]:
total_sales = np.dot(price_per_unit, units_sold)

In [27]:
print(total_sales)

[1900 2640 1430]
